### ISSUE TITLE
Say.js stoped working on Windows 10

### ISSUE THREAD

**Issue by that1estonian** [Marak/say.js#118]
```bash
Error: At line:1 char:1

    at Socket.<anonymous> (...\node_modules\say\platform\base.js:44:16)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:280:11)
    at Socket.Readable.push (_stream_readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

**Comment by that1estonian** [comment]
<a href="https://imgbb.com/"><img src="https://i.ibb.co/xjy5sK9/2021-05-09.png" alt="2021-05-09" border="0"></a>

That's cool 😆

**Comment by agreedrn** [comment]
Same thing happening to me, I have no idea how to fix it

**Comment by that1estonian** [comment]
> Same thing happening to me, I have no idea how to fix it

just allow threat in windows defender
