### ISSUE TITLE
Raspberry Pi

### ISSUE THREAD

**Issue by gcrev93** [Marak/say.js#41]
Does anyone know if say.js would work on raspbian since it is linux based?

**Comment by tlhunter** [comment]
It should work if you install the necessary modules:

```bash
sudo apt-get install festival festvox-kallpc16k
```

**Comment by gcrev93** [comment]
Awesome ok!

I'm going to try it

**Comment by tlhunter** [comment]
Please update this ticket with your discoveries.

**Comment by gcrev93** [comment]
It works!!! Voice a little weird but its understandable!

**Comment by natsu90** [comment]
@tlhunter thanks, I got below error in RPi and those command fixed it.

```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn festival ENOENT
    at exports._errnoException (util.js:870:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
    at Function.Module.runMain (module.js:469:11)
    at startup (node.js:136:18)
    at node.js:963:3
```

**Comment by marcocastignoli** [comment]
I got this error after installing festival
```internal/process/per_thread.js:189
      throw errnoException(err, 'kill');
      ^

Error: kill ESRCH
    at process.kill (internal/process/per_thread.js:189:13)
    at SayPlatformLinux.runStopCommand (/prj/barcode-photo/node_modules/say/platform/linux.js:41:13)
    at SayPlatformLinux.stop (/prj/barcode-photo/node_modules/say/platform/base.js:139:10)
    at Object.<anonymous> (/prj/barcode-photo/index.js:17:5)
    at Module._compile (internal/modules/cjs/loader.js:945:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:962:10)
    at Module.load (internal/modules/cjs/loader.js:798:32)
    at Function.Module._load (internal/modules/cjs/loader.js:711:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1014:10)
    at internal/main/run_main_module.js:17:11 {
  errno: 'ESRCH',
  code: 'ESRCH',
  syscall: 'kill'
}
```

**Comment by dyanakiev** [comment]
Works good for me, is there a way to install other voices?
