### ISSUE TITLE
Win32, speaks, but throws error "say.js export does not support platform win32"

### ISSUE THREAD

**Issue by mskogly** [Marak/say.js#64]
This error is thrown if I run the export example code from readme:

E:\Dropbox\Node\Sayjs>node say.js
Error: say.js export does not support platform win32
    at E:\Dropbox\Node\node_modules\say\index.js:134:16
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:611:11)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:598:3
Text has been spoken.
 Code 
// Export spoken audio to a WAV file
say.export("I'm sorry, Dave.", 'Cellos', 0.75, 'hal.wav', function(err) {
  if (err) {
    return console.error(err);
  }

  console.log('Text has been saved to hal.wav.');
});

**Comment by mskogly** [comment]
Known issue, sorry
