### ISSUE TITLE
Will support android?

### ISSUE THREAD

**Issue by songlairui** [Marak/say.js#82]
```bash
% node
> const a = require('say')
Thrown:
Error: new Say(): unsupported platorm! android
    at new Say (/data/data/com.termux/files/home/nodetts/node_modules/say/index.js:23:11)
    at Object.<anonymous> (/data/data/com.termux/files/home/nodetts/node_modules/say/index.js:27:18)
    at Module._compile (internal/modules/cjs/loader.js:734:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:745:10)
    at Module.load (internal/modules/cjs/loader.js:626:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:566:12)
    at Function.Module._load (internal/modules/cjs/loader.js:558:3)
    at Module.require (internal/modules/cjs/loader.js:663:17)
    at require (internal/modules/cjs/helpers.js:20:18)
>
```

When I require('say') on android + tmux + `pkg install nodejs`, the error above thrown

**Comment by tlhunter** [comment]
Perhaps, though this will require someone do a bunch of research

**Comment by songlairui** [comment]
> Perhaps, though this will require someone do a bunch of research

https://github.com/roccomuso/termux/blob/master/lib/cmds/ttsSpeak.js

here is a way to call ttsSpeak on android. But, it's not stable available( for example, it need run node with sudo above android Oreo )
