### ISSUE TITLE
linux, voice not found

### ISSUE THREAD

**Issue by darvin** [Marak/say.js#87]
homebridge       | Error: SIOD ERROR: unbound variable : en1_mbrola
homebridge       | 
homebridge       |     at Socket.child.stderr.once (/homebridge/node_modules/homebridge-alexa-hyundai/node_modules/say/platform/base.js:44:16)
homebridge       |     at Object.onceWrapper (events.js:277:13)
homebridge       |     at Socket.emit (events.js:189:13)
homebridge       |     at addChunk (_stream_readable.js:284:12)
homebridge       |     at readableAddChunk (_stream_readable.js:261:13)
homebridge       |     at Socket.Readable.push (_stream_readable.js:220:10)
homebridge       |     at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)

**Comment by darvin** [comment]
should have done 

```
voice_kal_diphone
```

not 

```
kal_diphone
```
